### ISSUE TITLE
Software Updates TODO

### ISSUE THREAD

**Issue by pj-roberts** [pj-roberts/analyze_thomson#30]
- [ ] GUI v0
  - [ ] Barebones fitting functionality
  - [ ] Support for fit settings feedback
  - [ ] Reduced data plots
  - [ ] Reduced data saving
  - [ ] Support for CTF datasets
  - [ ] Raman calibration/IF plotting

- [ ] Backend v1
  - [ ] Add correct wavelength bin file import
  - [ ] Update Raman calibration backend
